name: 'cms_hcc'
version: '0.1.0'
config-version: 2
profile: 'default'


vars:
    # The payment_year variable has a default of the current year
    # it can be changed here or during execution with
    # the syntax: dbt build --vars '{payment_year: 2022}'
    payment_year: 2023

    # Logic to be added for selecting the HCC model version
    # cms_hcc_model: CMS-HCC-V24

    # The following variables are required for the package models.
    # You should not have to make any changes to these.
    condition: >
        {% if var('cms_hcc_condition_override',none) is not none %}{{var('cms_hcc_condition_override')}}
        {%- else %}{{var('core_condition_override')}}
        {%- endif %}
    eligibility: >
        {% if var('cms_hcc_eligibility_override',none) is not none %}{{var('cms_hcc_eligibility_override')}}
        {%- else %}{{var('core_eligibility_override')}}
        {%- endif %}
    medical_claim: >
        {% if var('cms_hcc_medical_claim_override',none) is not none %}{{var('cms_hcc_medical_claim_override')}}
        {%- else %}{{var('core_medical_claim_override')}}
        {%- endif %}



model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
